singleuser:
  image:
    name: europe-west4-docker.pkg.dev/irtm-2025-2026/irtm-repo/course-image
    tag: v6  # Let op: v6!
  lifecycleHooks: {} # We halen de copy-opdracht hier weg
  storage:
    type: dynamic
    capacity: 10Gi
  cpu:
    limit: 1
    guarantee: 0.5
  memory:
    limit: 4G
    guarantee: 2G

hub:
  config:
    JupyterHub:
      admin_users:
        - jan-docent
    Authenticator:
      admin_users:
        - jan-docent
    DummyAuthenticator:
      password: "DACS2026"

proxy:
  https:
    enabled: true
    hosts:
      - irtm-course-um.nl
      - www.irtm-course-um.nl
    letsencrypt:
      contactEmail: j.scholtes@maastrichtuniversity.nl